repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        exclude: ^(venv/|migrations/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^(venv/|migrations/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
      
        args:
          - --config-file=mypy.ini
          - --explicit-package-bases
          - --ignore-missing-imports
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
          - python-dotenv
          - djangorestframework
          - djangorestframework-simplejwt
          - psycopg2-binary
          - dj-database-url
          - pymysql
          - types-PyMySQL
          - drf-spectacular
          - drf-spectacular-sidecar
          
        exclude: ^(venv/|migrations/|tests/)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-q", "--skip", "B101"]
        exclude: ^(venv/|migrations/|tests/)
